### ISSUE TITLE
Cannot use login example

### ISSUE THREAD

**Issue by nguyendev** [ampproject/amp.dev#3355]
![image](https://user-images.githubusercontent.com/10234503/72033994-69503900-32c6-11ea-9f80-e27da2417619.png)

**Comment by sebastianbenz** [comment]
It works locally, but is broken on deploy. Seems like a problem with how we resolve template file from within samples (//cc @matthiasrohmer ):

```
A 2020-01-13T09:16:33.845724400Z [TIMING] amp.dev/documentation/examples/api/amp-access/login?rid=amp-Mvd3xt4Ij1auZn9M88Xl7A&url=https%3A%2F%2Famp.dev%2Fdocumentation%2Fexamples%2Fcomponents%2Famp-access%2Findex.html&return=https%3A%2F%2Fcdn.ampproject.org%2Fv0%2Famp-login-done-0.1.html%3Furl%3Dhttps%253A%252F%252Fplayground.amp.dev%252F%253Furl%253Dhttps%25253A%25252F%25252Fpreview.amp.dev%25252Fdocumentation%25252Fexamples%25252Fcomponents%25252Famp-access-laterpay%2526format%253Dwebsites%2526_gl%253D1*am5lot*_ga*YW1wLXZXTmIwRXFhanBtMkU0eHp5TmlFVFE.%2526mode%253DiPhone%252BXs%252BMax 0.006s [500]
 
A 2020-01-13T09:16:33.840098831Z     at handleLogin (/usr/src/app/examples/api/amp-access/index.js:74:26)
 
A 2020-01-13T09:16:33.840093581Z     at Object.render (/usr/src/app/node_modules/nunjucks/index.js:92:14)
 
A 2020-01-13T09:16:33.840088506Z     at Environment.render (/usr/src/app/node_modules/nunjucks/src/environment.js:360:10)
 
A 2020-01-13T09:16:33.840082955Z     at Environment.getTemplate (/usr/src/app/node_modules/nunjucks/src/environment.js:321:9)
 
A 2020-01-13T09:16:33.840077832Z     at Object.asyncIter (/usr/src/app/node_modules/nunjucks/src/lib.js:286:3)
 
A 2020-01-13T09:16:33.840072870Z     at next (/usr/src/app/node_modules/nunjucks/src/lib.js:280:7)
 
A 2020-01-13T09:16:33.840067503Z     at /usr/src/app/node_modules/nunjucks/src/environment.js:339:9
 
A 2020-01-13T09:16:33.840056769Z     at handle (/usr/src/app/node_modules/nunjucks/src/environment.js:329:11)
 
A 2020-01-13T09:16:33.840051054Z     at next (/usr/src/app/node_modules/nunjucks/src/lib.js:282:7)
 
A 2020-01-13T09:16:33.840042182Z     at createTemplate (/usr/src/app/node_modules/nunjucks/src/environment.js:290:15)
 
A 2020-01-13T09:16:33.839994461Z [ERROR] Error: template not found: /usr/src/app/examples/api/amp-access/login.html
 
A 2020-01-13T09:16:33.773574783Z [TIMING] amp.dev/documentation/guides-and-tutorials/start/create/basic_markup/ 0.004s [200]
 
A 2020-01-13T09:16:33.771102096Z [TIMING] playground.amp.dev/documentation/examples/api/amp-access/login?rid=amp-Mvd3xt4Ij1auZn9M88Xl7A&url=https%3A%2F%2Famp.dev%2Fdocumentation%2Fexamples%2Fcomponents%2Famp-access%2Findex.html&return=https%3A%2F%2Fcdn.ampproject.org%2Fv0%2Famp-login-done-0.1.html%3Furl%3Dhttps%253A%252F%252Fplayground.amp.dev%252F%253Furl%253Dhttps%25253A%25252F%25252Fpreview.amp.dev%25252Fdocumentation%25252Fexamples%25252Fcomponents%25252Famp-access-laterpay%2526format%253Dwebsites%2526_gl%253D1*am5lot*_ga*YW1wLXZXTmIwRXFhanBtMkU0eHp5TmlFVFE.%2526mode%253DiPhone%252BXs%252BMax 0.020s [301]
 
A 2020-01-13T09:16:33.764364288Z [TIMING] amp.dev/documentation/examples/api/amp-access/login?rid=amp-Mvd3xt4Ij1auZn9M88Xl7A&url=https%3A%2F%2Famp.dev%2Fdocumentation%2Fexamples%2Fcomponents%2Famp-access%2Findex.html&return=https%3A%2F%2Fcdn.ampproject.org%2Fv0%2Famp-login-done-0.1.html%3Furl%3Dhttps%253A%252F%252Fplayground.amp.dev%252F%253Furl%253Dhttps%25253A%25252F%25252Fpreview.amp.dev%25252Fdocumentation%25252Fexamples%25252Fcomponents%25252Famp-access-laterpay%2526format%253Dwebsites%2526_gl%253D1*am5lot*_ga*YW1wLXZXTmIwRXFhanBtMkU0eHp5TmlFVFE.%2526mode%253DiPhone%252BXs%252BMax 0.005s [500]
 
A 2020-01-13T09:16:33.764251437Z     at handleLogin (/usr/src/app/examples/api/amp-access/index.js:74:26)
 
A 2020-01-13T09:16:33.764243563Z     at Object.render (/usr/src/app/node_modules/nunjucks/index.js:92:14)
 
A 2020-01-13T09:16:33.764216941Z     at Environment.render (/usr/src/app/node_modules/nunjucks/src/environment.js:360:10)
 
A 2020-01-13T09:16:33.764210983Z     at Environment.getTemplate (/usr/src/app/node_modules/nunjucks/src/environment.js:321:9)
 
A 2020-01-13T09:16:33.764204914Z     at Object.asyncIter (/usr/src/app/node_modules/nunjucks/src/lib.js:286:3)
 
A 2020-01-13T09:16:33.764198623Z     at next (/usr/src/app/node_modules/nunjucks/src/lib.js:280:7)
 
A 2020-01-13T09:16:33.764192579Z     at /usr/src/app/node_modules/nunjucks/src/environment.js:339:9
 
A 2020-01-13T09:16:33.764172397Z     at handle (/usr/src/app/node_modules/nunjucks/src/environment.js:329:11)
 
A 2020-01-13T09:16:33.764164221Z     at next (/usr/src/app/node_modules/nunjucks/src/lib.js:282:7)
 
A 2020-01-13T09:16:33.764121576Z     at createTemplate (/usr/src/app/node_modules/nunjucks/src/environment.js:290:15)
 
A 2020-01-13T09:16:33.762959828Z [ERROR] Error: template not found: /usr/src/app/examples/api/amp-access/login.html
 
```

**Comment by rajavijaysingh** [comment]
any updates on this issue
still not working

https://amp.dev/documentation/guides-and-tutorials/develop/login_requiring/login

@mrjoro @sebastianbenz 
it would be good if this could be sorted as a working example would help in understanding the login integration documentation better
