### ISSUE TITLE
Trouble importing all of the documents

### ISSUE THREAD

**Issue by DerekNonGeneric** [ampproject/amp.dev#4092]
I will have to separate these commits out a little better. I had trouble importing all of the documents. Not all of them came in when running `npm run bootstrap` or even by simply running `npx gulp importAll`. I think the flaky GitHub downloads leads to winding up w/ documents missing — a bit of a hassle. :/ Anyways, I'll get back to this in a short while. Thank you for your patience.

_Originally posted by @DerekNonGeneric in https://github.com/ampproject/amp.dev/pull/3346#issuecomment-644847783_

**Comment by DerekNonGeneric** [comment]
To reproduce this bug:

1. `nvm install --lts`
2. `npm install`
3. `npm run lint` (be sure it passes)
4. `npm run bootstrap`
5. `npm run lint` (this fails)

Actual:

```
[12:35:57 PM] [Reference checker] › ✖  error     No matching document found for /content/amp-dev/documentation/components/amp-access/0.1/iframe-api/README.md. Needs manual fixing. (First found in /mnt/c/orgs/ampproject/amp.dev/pages/content/amp-dev/documentation/components/reference/amp-subscriptions-v0.1.md)
[12:35:57 PM] [Reference checker] › ✖  error     No matching document found for /content/amp-dev/documentation/components/amp-subscriptions-google/amp-subscriptions-google.md. Needs manual fixing. (First found in /mnt/c/orgs/ampproject/amp.dev/pages/content/amp-dev/documentation/components/reference/amp-subscriptions-v0.1.md)


[12:36:12] 'lintGrow' errored after 33 s
[12:36:12] Error: 2 broken links and 0 wrong anchors found
    at Pumpify.<anonymous> (/mnt/c/orgs/ampproject/amp.dev/platform/lib/tools/growReferenceChecker.js:177:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[12:36:12] 'lintAll' errored after 33 s
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! amp-dev@1.0.5 lint: `npx gulp lintAll`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the amp-dev@1.0.5 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Expected (some similar):

```
✔ success All references intact!
```
