### ISSUE TITLE
Fix errors in translated documents

### ISSUE THREAD

**Issue by patrickkettner** [ampproject/amp.dev#4780]
I wasn't able to debug this tonight, will do it asap unless anyone else has time to check it out

```sh
[2:18:16 AM] [Reference checker] › ℹ  info      Encountered multiple possible matches for 2 documents:
[2:18:16 AM] [Reference checker] › ☐  pending   /content/amp-dev/documentation/examples/previews/Live_Blog.html
[2:18:16 AM] [Reference checker] › ☐  pending   -- /content/amp-dev/documentation/examples/documentation/Live_Blog.html
[2:18:16 AM] [Reference checker] › ☐  pending   -- /content/amp-dev/documentation/examples/samples-and-templates/Live_Blog.html
[2:18:16 AM] [Reference checker] › ☐  pending   /content/amp-dev/documentation/examples/previews/Comment_Section.html
[2:18:16 AM] [Reference checker] › ☐  pending   -- /content/amp-dev/documentation/examples/documentation/Comment_Section.html
[2:18:16 AM] [Reference checker] › ☐  pending   -- /content/amp-dev/documentation/examples/samples-and-templates/Comment_Section.html
[02:18:16] 'lintGrow' errored after 5.11 s
[02:18:16] Error: 2 broken links and 0 wrong anchors found
    at Pumpify.stream.on (/Users/patrickkettner/projects/amp.dev/platform/lib/tools/growReferenceChecker.js:177:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by matthiasrohmer** [comment]
I think I fixed the build-blocking issues with https://github.com/ampproject/amp.dev/pull/4781, https://github.com/ampproject/amp.dev/commit/218bce23ddf7052d54ddb21477e7076575397e08 and https://github.com/ampproject/amp.dev/commit/2b87b5921c8afa90532105ff29dff9bbf9a957b6.

We need to be a little more careful when translating the documents - especially with our special tags. Some of them are still broken:

![Bildschirmfoto 2020-10-04 um 13 04 05](https://user-images.githubusercontent.com/12857772/95013672-1ed7cf00-0642-11eb-97a3-25f30de47352.png)
